# Generated by Django 4.1 on 2022-10-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('author_name', models.CharField(max_length=20)),
                ('book_price', models.IntegerField()),
                ('book_pages', models.IntegerField()),
                ('publication', models.CharField(max_length=20)),
            ],
        ),
    ]
