# Generated by Django 4.1 on 2022-10-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_library_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='book_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='library',
            name='book_pages',
        ),
        migrations.RemoveField(
            model_name='library',
            name='publication',
        ),
        migrations.AddField(
            model_name='library',
            name='type_of_book',
            field=models.CharField(default='n', max_length=20),
        ),
        migrations.AlterField(
            model_name='library',
            name='is_deleted',
            field=models.CharField(max_length=2),
        ),
    ]
