# Generated by Django 4.1 on 2022-10-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_book_price_library_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='type_of_book',
            field=models.CharField(default='', max_length=20),
        ),
    ]
