# Generated by Django 4.1 on 2022-10-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_library_type_of_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='is_deleted',
            field=models.CharField(default='n', max_length=2),
        ),
    ]
